/*
 * This source file was generated by the Gradle 'init' task
 */
package lesson0;

public class App {

    public static void main(String[] args) {
        Ex1 x = new Ex1();
        x.demo();
    }
}
