/*
 * This source file was generated by the Gradle 'init' task
 */
package lesson0;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void firstEx() {
        // my code here
    }

    public static void main(String[] args) {
        firstEx();
    }
}
